# Generated by Django 4.1.3 on 2022-12-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0006_alter_comment_post_alter_like_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
